### ISSUE TITLE
Login logs

### ISSUE THREAD

**Issue by redskam** [linuxforphp/filebrowser#8]
Hello,
I have been using filebrowser without trouble for a few weeks now, and everything works great, but I don't know where/how to find the logins logs.
Are they disabled by default ? Since there is no login event yet, I wanted to read the logs so that if someone connects I can execute custom commands.
How should I proceed ?

**Comment by andrewscaya** [comment]
Hi @redskam,

Sorry for the late reply!

The log file is determined by the configuration.php file, and the line that you are looking for is: "'log_file' => APP_ROOT_DIR . DIR_SEP . 'private' . DIR_SEP . 'logs' . DIR_SEP . 'app.log',". (Ref.: https://filebrowser.readthedocs.io/en/latest/configuration_basic.html#basic-configuration).

If you need to log information about each and every login, you might have to configure the Monolog service further: https://filebrowser.readthedocs.io/en/latest/configuration/logging.html#configuring-the-logging-service.

Otherwise, you might have to add your own custom service, depending on what you need to do, in order to get the logs that you want.

Many thanks for your interest in the File Browser project!

Best regards,

Andrew

/cc @jcroy

**Comment by redskam** [comment]
Thank you for the answer ! I had put that idea on a shelve, but I'll look into it again. When I opened the issue, I was also confused on where everything was stored because I was using the docker / podman setup. Now that I know where to find everything, I don't think I'll have too much trouble achieving my goal, so I'll close this ticket.
Thank you for this cool and useful project by the way!
